language: r

before_install:
 - openssl aes-256-cbc -K $encrypted_77ab6371db8f_key -iv $encrypted_77ab6371db8f_iv -in github_deploy_key.enc -out github_deploy_key -d

install:
  - R -e "0" --args --bootstrap-packrat
  
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh

script:
- "./_build.sh"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./_deploy.sh; else echo "PR so
  not deploying"; fi